# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
notifications:
  email:
    # recipients:
    #   - one@example.com
    on_success: never # default: change
    on_failure: always # default: always
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
before_install: pip install codecov pytest-cov
install: pip install -r requirements/dev.txt
#before_script: flask lint
script:
  - py.test --verbose --cov=wersav tests/
after_success: codecov